// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCM2sqJmkNi-sUrGwEFFyQHhBFAqQkXfI',
    appId: '1:991063967881:web:81f0cc16df0ac8e5dd9e58',
    messagingSenderId: '991063967881',
    projectId: 'agua-para-todos-e3fa2',
    authDomain: 'agua-para-todos-e3fa2.firebaseapp.com',
    storageBucket: 'agua-para-todos-e3fa2.appspot.com',
    measurementId: 'G-Q8FP63BK3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESMm_UJZnhKuRx0NBnbh4FVWk5vsCHzM',
    appId: '1:991063967881:android:ed166852c07aadf3dd9e58',
    messagingSenderId: '991063967881',
    projectId: 'agua-para-todos-e3fa2',
    storageBucket: 'agua-para-todos-e3fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvtFhK89Lo1jRz7TbCSCbrqj75C07-vM',
    appId: '1:991063967881:ios:477437722675067ddd9e58',
    messagingSenderId: '991063967881',
    projectId: 'agua-para-todos-e3fa2',
    storageBucket: 'agua-para-todos-e3fa2.appspot.com',
    iosClientId: '991063967881-3777mh19s56e26r5e48r1jgngpqup7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aguaParaTodos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrvtFhK89Lo1jRz7TbCSCbrqj75C07-vM',
    appId: '1:991063967881:ios:79cb5be5a54705dfdd9e58',
    messagingSenderId: '991063967881',
    projectId: 'agua-para-todos-e3fa2',
    storageBucket: 'agua-para-todos-e3fa2.appspot.com',
    iosClientId: '991063967881-pc6jnj0nl93etap86eg51s6r6i37j4l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aguaParaTodos.RunnerTests',
  );
}
